### ISSUE TITLE
Ask elementary developers to implement it

### ISSUE THREAD

**Issue by Suzie97** [pongloongyeat/drive-daemon#1]
Hey, I was wondering if you were interested in implementing this by default on elementary OS. You can ask the devs, I think they might be interested as it a useful daemon.

**Comment by pongloongyeat** [comment]
That would be a plan for sure! I'll bring it up either via GitHub discussions or on Slack. However, this is nowhere near complete and is still missing certain features I'd like i.e. clicking on the notification should mount one of the volumes, but which?

**Comment by pongloongyeat** [comment]
I have filed this as a discussion, rather than asking to adopt this repo. It can be tracked [here](https://github.com/elementary/notifications/discussions/116).
